import '../styles/globals.css';
import { Analytics } from '@vercel/analytics/react';
import { Roboto_Mono } from 'next/font/google';
import { Providers } from './providers';
const robotoMono = Roboto_Mono({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Home',
  description: 'Generated by create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ja"
      className={`h-10 text-center
        bg-gradient-to-r
        from-slate-900 via-gray-800 to-indigo-900 ${robotoMono.className}`}
    >
      <Analytics />
      <body>{children}</body>
    </html>
  );
}
