import '../../styles/globals.css';
import { Analytics } from '@vercel/analytics/react';

export const metadata = {
  title: '制作途中',
  description: 'Generated by create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ja"
      className=" h-10 text-center
        bg-gradient-to-r
        from-slate-900 via-gray-800 to-indigo-900
        "
    >
      <Analytics />
      <body>{children}</body>
    </html>
  );
}
